import './global.css';
import Sidebar from './lib/components/sidebar/sidebar';

export const metadata = {
  title: 'Welcome to algo-visualizer',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Sidebar />
      </body>
    </html>
  );
}
